insert into PHONE (model, availability) values ('Samsung Galaxy S9', 'yes');
insert into PHONE (model, availability) values ('Samsung Galaxy S8', 'yes');
insert into PHONE (model, availability) values ('Samsung Galaxy S8', 'yes');
insert into PHONE (model, availability) values ('Motorola Nexus 6', 'yes');
insert into PHONE (model, availability) values ('Oneplus 9', 'yes');
insert into PHONE (model, availability) values ('Apple iPhone 13', 'yes');
insert into PHONE (model, availability) values ('Apple iPhone 12', 'yes');
insert into PHONE (model, availability) values ('Apple iPhone 11', 'yes');
insert into PHONE (model, availability) values ('iPhone X', 'yes');
insert into PHONE (model, availability) values ('Nokia 3310', 'yes');